---
- include: webupd8.yml

- name: Pause
  pause: seconds=60

- name: Automatically select the Oracle License
  tags: java
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: Update apt
  command: apt-get update

- name: Pause
  pause: seconds=5
  
- name: Install Java
  tags: java
  command: apt-get install -y oracle-{{item}}-installer
  with_items: java_versions
