- name: Undeploy and Distribute
  hosts: 
  - tag_Name_Accio-Frontend-01
  - tag_Name_Accio-Backend-01
  user: ubuntu
  sudo: true
  gather_facts: false
  roles:
      - undeploy
      - distribute

- name: Run Frontend
  hosts: 
  - tag_Name_Accio-Frontend-01
  user: ubuntu
  sudo: true
  gather_facts: false
  roles:
      - deploy-frontend


- name: Run Backend
  hosts: 
  - tag_Name_Accio-Backend-01
  user: ubuntu
  sudo: true
  gather_facts: false
  roles:
      - deploy-backend      