---

- name: Send distribution
  hosts:
  - tag_Name_reducto-frontend-01
  user: ubuntu
  sudo: true
  gather_facts: false
  tasks:

      - name: Remove old Dist
        command: rm -rf /usr/local/reducto-dist
        ignore_errors: yes

      - name: Copy project Dist
        copy: src=../target/reducto-dist dest=/usr/local/


