---

- name: Deploy Seed
  hosts:
  - tag_Name_reducto-seed-01
  user: ubuntu
  sudo: true
  gather_facts: false
  tasks:
      
      - name: Kill previous run
        command: stop reducto-seed N=1
        ignore_errors: yes

      - name: Remove old Dist
        command: rm -rf /usr/local/reducto-dist
        ignore_errors: yes
        
      - name: Copy project Dist
        copy: src=../target/reducto-dist dest=/usr/local/

      - name: Run Seed Akka
        command: start reducto-seed N=1