---

- name: Deploy Supervisor
  hosts:
  - tag_Name_reducto-supervisor-01
  user: ubuntu
  sudo: true
  gather_facts: false
  tasks:
      
      - name: Kill previous run
        command: stop reducto-supervisor N=1
        ignore_errors: yes

      - name: Copy project Dist
        copy: src=../target/reducto-dist dest=/usr/local/

      - name: Run supervisor Akka
        command: start reducto-supervisor N=1